contexts:
  - int
  - acc
  - local-db
  - test-deployment

executions:
  - name: int
    output: 
      name: int.env
      directory: generated
    kube-context: kind-kind
    contexts:
      - int
  - name: int-local
    output: 
      name: int-local.env
      directory: generated
    kube-context: kind-kind
    contexts:
      - int
      - local-db
  - name: deployment-test
    output: 
      name: deployment.env
      directory: generated
    kube-context: kind-kind
    contexts:
      - test-deployment

sources:
  - type: ConfigMap
    namespace: default
    name: configmap1
  - type: ConfigMap
    name: configmap-ns1
    namespace: ns1
  - type: Secret
    name: secret1
  - type: Secret
    name: secret1-ns1
    namespace: ns1
    contexts:
      exclude:
        - local-db
  - type: EnvFile
    path: samples/int.env
    contexts:
      include:
        - int
    transformations:
      - type: prefix
        target: key
        value: "APP_"
      - type: base64_encode
        target: value
        variables:
          - APP_DB_HOST
  - type: EnvFile
    path: samples/acc.env
    contexts:
      include:
        - acc
  - type: EnvFile
    path: samples/local.db.env
    contexts:
      include:
        - local-db
    variables:
      exclude:
        - ^ANOT.*
        - SOMETHING
    transformations:
      - type: file
        target: value
        output: files/file.txt
        key: FILE
        variables:
          - FILE
      - type: absolute_path
        target: value
        variables:
          - FILE
  - type: Vars
    name: inline vars
    vars:
      - name: ONE
        value: TWO
      - name: THREE
        value: FOUR
  - type: Deployment
    name: busybox-deployment
    containers:
      - busybox-1
      - busybox-2
    volumeMountKeyMappings:
      - kind: ConfigMap
        name: configmap-file
        mappings:
          file1.json: FILE1
          file2.json: FILE2
    contexts:
      include:
        - test-deployment
