apiVersion: v1
kind: Namespace
metadata:
  name: ns1
  labels:
    name: ns1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  KEY1: value1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ns1
  namespace: ns1
data:
  KEYNS1: valuens1
---
apiVersion: v1
kind: Secret
metadata:
  name: secret1
data:
  SECRET1: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-file
data:
  file1.json: |
    {
      "a": "b"
    } 
  file2.json: |
    {
      "c": "d"
    }   
---
apiVersion: v1
kind: Secret
metadata:
  name: secret1-ns1
  namespace: ns1
data:
  SECRETNS1: eW8K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      volumes:
        - name: configmap-mount
          configMap:
            name: configmap-file
      containers:
        - name: busybox-1
          image: busybox
          command: ["sleep", "3600"]
          env:
            - name: FIRST
              value: "1"
            - name: SECOND
              value: "2"
            - name: KEY1
              value: FROM_DEPLOYMENT
          envFrom:
            - configMapRef:
                name: configmap1
            - secretRef:
                name: secret1
        - name: busybox-2
          image: busybox
          command: ["sleep", "3600"]
          volumeMounts:
            - mountPath: /tmp
              name: configmap-mount
              readOnly: true
